name: harishanbalagan
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  flutter: 3.38.6
  sdk: 3.10.7

dependencies:
  animated_text_kit: ^4.2.2

  cupertino_icons: ^1.0.8
  dart_mappable: ^4.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  go_router: ^17.0.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.0
  flutter_gen_runner: ^5.4.0

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/src/gen/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/data/
